### ISSUE TITLE
Only word mode works

### ISSUE THREAD

**Issue by simonsmith** [ice9js/ace-jump-sublime#15]
Hey, 

I can only get `super+shift+;` to work. None of the other hotkeys seem to work. I have tried remapping them to different keys and/or adding the `alt` key but no dice.

I'm on ST3 and Mac OS

**Comment by ice9js** [comment]
Hey,

That's weird as I have the same setup and I made sure it works.
My suggestions would be to double check if there are no overlapping shortcuts, and also check the console (Ctrl + ~) for any errors or messages after attempting to launch a command.

Let me know if you found anything and I'll dig into it.

**Comment by simonsmith** [comment]
You were right, I had multiple conflicting plugins.

In case anyone else needs it I used `sublime.log_commands(True)` to show which ones were running and then removed the keymappings

Thanks for this plugin, works really nicely
