### ISSUE TITLE
Add possibility to jump after found instance

### ISSUE THREAD

**Issue by ghost** [ice9js/ace-jump-sublime#20]
If I understood it correctly, right now there is no way to make the plugin jump behind a character or word or whathaveyou. This'd be a great feature to have. Maybe one could make it work by holding down a modifier key while pressing on the label.

**Comment by ice9js** [comment]
It is a feature worth considering, however we'll need to figure out a different way to trigger this behavior.
AceJump compares input characters to labels, and using a modifier key wouldn't work here.

Also, how do you feel about label placement ? Should they also be moved as well ?

**Comment by ghost** [comment]
How do you mean? The labels are "on top" of the instances right now, no? I think that's fine. But while we're at it: I'd love if the matching view would respect my theme/way of displaying things. Right now it jumps between the [MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing) way of display things  and ace jumps "theme":

<img width="767" alt="screen shot 2015-08-17 at 23 38 01" src="https://cloud.githubusercontent.com/assets/423471/9317002/0b5b29ec-4539-11e5-9432-e21277109a80.png">

<img width="767" alt="screen shot 2015-08-17 at 23 38 10" src="https://cloud.githubusercontent.com/assets/423471/9317007/100c1064-4539-11e5-8306-c38e3b7a6b76.png">

It would be awesome if would not jump back and forth themewise.

P.S.: I also [second the request that acejump should't show line numbers](https://github.com/ice9js/ace-jump-sublime/issues/19), if I don't have enabled them.

**Comment by ice9js** [comment]
Interesting, it should only change the syntax highlighting, and definitely shoudn't switch whole themes. This could be related to why line numbers are showing up. Please make a separate issue for this.

As far as this feature request goes, if you come up with how you'd like to trigger this behavior without using a modifier key, I could implement this.

**Comment by ghost** [comment]
Well, another way to do it would be to initiate acejump with a modifier key. So essentially one would have to duplicate all the modes and add the desired behaviour (that is, jumping behind a certain symbol). Maybe that works. I'll see if I can come up with any other ideas.

P.S.: [New issue for the theme switching problem added](https://github.com/ice9js/ace-jump-sublime/issues/21).

**Comment by ice9js** [comment]
Alright, just see what you're comfortable with. As I use emacs keybindings and have no need for this feature, I think it will be best to leave this decision to a potential user.

**Comment by ghost** [comment]
So… it is possible to get the desired behaviour as long as you use emacs keybindings? Care to describe how this'd work?

**Comment by ice9js** [comment]
Well, I set up sublime keybindings for moving the cursor in the same way as in emacs.
If I want to jump to the back of a word, I jump to the front, and then press `Alt+f` which moves the cursor to the end of the word.
But this is not a feature of AceJump, just some personal sublime configuration.

**Comment by ghost** [comment]
Ah, I see. I do something similar then already `alt+arrow key`. Also, I think [the way I described how the feature should work here](https://github.com/ice9js/ace-jump-sublime/issues/20#issuecomment-132156968) is the best way to go forward. This way, people can use their own keybindings.

**Comment by ice9js** [comment]
Functionallity added in #23.
