### ISSUE TITLE
themes get switched when using acejump

### ISSUE THREAD

**Issue by ghost** [ice9js/ace-jump-sublime#21]
Reference would be [this comment](https://github.com/ice9js/ace-jump-sublime/issues/20#issuecomment-131970126). I'll just quote the relevant part here:

> I'd love if the matching view would respect my theme/way of displaying things. Right now it jumps between the [MarkdownEditing](https://github.com/SublimeText-Markdown/MarkdownEditing) way of display things  and ace jumps "theme":

<img width="767" alt="screen shot 2015-08-17 at 23 38 01" src="https://cloud.githubusercontent.com/assets/423471/9317002/0b5b29ec-4539-11e5-9432-e21277109a80.png">

<img width="767" alt="screen shot 2015-08-17 at 23 38 10" src="https://cloud.githubusercontent.com/assets/423471/9317007/100c1064-4539-11e5-8306-c38e3b7a6b76.png">

> It would be awesome if would not jump back and forth themewise.

P.S.: [Might be a duplicate of this issue](https://github.com/ice9js/ace-jump-sublime/issues/19).

**Comment by ice9js** [comment]
Should be fixed in #23.
