### ISSUE TITLE
Always in Select Mode

### ISSUE THREAD

**Issue by bwiggs** [ice9js/ace-jump-sublime#22]
Whenever I perform a jump, text is always selected. 

I'm using `Super+Shift+;` then typing `r` to get to the first `require` call. Notice that the text from the beginning of the document to the character I select is selected.

See screencast: 
![ace-jump bug](https://cloud.githubusercontent.com/assets/7358/9693459/3e2b1cca-5316-11e5-8c6d-8165d2d7459d.gif)

OSX 10.10.4 - ST3 b3083

**Comment by bwiggs** [comment]
Here's what I'm getting in the console.

```
command: easy_motion {"select_text": true}
```

**Comment by ice9js** [comment]
Sorry for the late response, I couldn't get back to you earlier.

It looks to me as if you have the EasyMotion plugin installed side by side with AceJump. Some keyboard shortcuts overlap. In this case, cmd+shift+; in easy motion selects the text.
To fix this, either remove the EasyMotion plugin, or override the keyboard shortcuts for EasyMotion or AceJump.

**Comment by bwiggs** [comment]
Oh, right! Thanks! Feeling a bit silly.

**Comment by ice9js** [comment]
I'm glad I could help.
