### ISSUE TITLE
Characte mode doesnt work

### ISSUE THREAD

**Issue by bwiggs** [ice9js/ace-jump-sublime#24]
On my mac `super+shift+'` does nothing. Nothing happening in console either. 

What's the best way to debug this?

**Comment by ice9js** [comment]
Did you check you key shortcut settings ? Make sure there isn't anything else that's set to `super+shift+'`, or change the binding for ace jump.

**Comment by bwiggs** [comment]
Is there a way in TM to see all my current key bindings across extensions?

**Comment by ice9js** [comment]
I don't think so, but the following line will log everything you do in the console, so you can see which commands you're actually triggering.

```
sublime.log_commands(True)
```
