### ISSUE TITLE
Runs out of selections at 'Z' - could it extend to numerical values?

### ISSUE THREAD

**Issue by benfrain** [ice9js/ace-jump-sublime#26]
First of all - I love this functionality. Thanks for the great plugin.

Edge case so something for a rainy day ;)

On a single page view, this works great. However, on a split view, on a large monitor, I run out of symbols in line view. E.g. if I enter line view and I have 100 lines on screen across two panes I only get indicators up to `Z` - any way this can be extended with numbers? I know it will only get another 10 lines but just a thought.

Thanks again for making this.

**Comment by ice9js** [comment]
Hi,

The labels are batched. Just press enter and it will highlight the next set of lines or characters.
If you want to add more label characters, you can do this yourself by overriding the labels string in the settings (Preferences > Package Settings > AceJump).

I hope this helps.

**Comment by benfrain** [comment]
Amazing! :+1: Now I understand that part of the readme!!
