### ISSUE TITLE
How to fix contrast in material theme?

### ISSUE THREAD

**Issue by rawaludin** [ice9js/ace-jump-sublime#33]
Hi, I really love this plugin. Currently, I'm using Material theme plugin https://github.com/equinusocio/material-theme. But, the contrast looks weird. Here's what I got:

![screen shot 2015-12-03 at 8 29 56 pm](https://cloud.githubusercontent.com/assets/1274849/11561875/cecb775c-99fc-11e5-80b7-bbddcb529e5e.png)

I'm really can't see the mark. For inspiration, using solarized dark, here's what I got:
![screen shot 2015-12-03 at 8 31 52 pm](https://cloud.githubusercontent.com/assets/1274849/11561886/f7a3884a-99fc-11e5-9b43-531deeb93982.png)

What should I do to fix this? Thanks..

**Comment by ice9js** [comment]
Hi,

That looks rather like a theme issue to me, but worry not as the solution is already implemented.
Go to `Preferences > Package Settings > AceJump > Key Bindings - User` and add the following setting:

``` json
{
    "labels_scope": "invalid"
}
```

It basically says, that AceJump should use the 'invalid' highlighting from your theme to highlight the labels. This is the default value, but obviously doesn't work for all themes out there, so you'll need to tweak this setting and see what works for you.

You can find a list of available highlighting scopes here: http://stackoverflow.com/a/21914803/4782314 .
Let me know if that solves the issue.

**Comment by rawaludin** [comment]
whoaa.. thats a lot of options. Let see what'll work..

**Comment by rawaludin** [comment]
Thanks its worked. I go with `string`, which result in this:
![screen shot 2015-12-03 at 9 09 34 pm](https://cloud.githubusercontent.com/assets/1274849/11562705/35839646-9a02-11e5-9e8e-bc2b7861fbfc.png)

**Comment by ice9js** [comment]
I'm glad I could help.

**Comment by huuson235** [comment]
> I'm glad I could help.

Could you provide your acejump settings to change the highlight color?
