### ISSUE TITLE
After install on windows no keymappings set up

### ISSUE THREAD

**Issue by togakangaroo** [ice9js/ace-jump-sublime#34]
Both the User and Default files under Package Settings>AceJump are blank

**Comment by togakangaroo** [comment]
Actually, in general

```
 Unable to open /C/Users/gmaue/AppData/Roaming/Sublime Text 3/Packages/AceJump/Default (Windows).sublime.keymap
```

nothing exists in Pcakges/AceJump - its all in InstalledPackages

**Comment by bangedorrunt** [comment]
@togakangaroo, this is because there were incorrect path names in Sublime Menu. I submitted this PR #35 to fix this issue

**Comment by ice9js** [comment]
@babygau, thank you for the pull request resolving this issue.

**Comment by bangedorrunt** [comment]
@ice9js you're welcome. Thank you for giving us this such great plugin. It's working so well with `Vintageous` :+1:
