### ISSUE TITLE
How to jump to the braces character?

### ISSUE THREAD

**Issue by GordeyChernyy** [ice9js/ace-jump-sublime#36]
Hi, is there any option to jump to the braces or any custom character?

**Comment by ice9js** [comment]
Hi!

You should be able to jump to special characters just like you would to letters. You might encounter some issues in word mode as they aren't really word characters. Character mode should work all right though.

**Comment by GordeyChernyy** [comment]
Oh, thank you very much! I was in word mode and in formatting style like `MonoBehaviour{` the `{` character was selectable while same characters was unavailable.

**Comment by ice9js** [comment]
I'm glad I could help.
