### ISSUE TITLE
If character is last in line, go to after character instead of before

### ISSUE THREAD

**Issue by eorroe** [ice9js/ace-jump-sublime#38]
For example:

``` JS
console.log('logging');
```

call `ace_jump_char`

Char: `;`

``` JS
console.log('logging');|
```

I'm not sure how many people would prefer this, but could this be an option in the settings:

Its much easier to use backspace than the delete key if I want to delete the last character

**Comment by stoivo** [comment]
:+1:

**Comment by eorroe** [comment]
This is not the same thing, what I mean is that it stays jumping in front of the character, but when I'm aiming to jump to the last character I always find myself needing to jump to the end if its the last character only. So that I can easily hit backspace instead of right arrow -> backspace or the delete key.

I'm not sure how many people have this problem, and perhaps they do just haven't reported it and doesn't bother them, but if this could easily be implemented via a setting that'd be nice thanks.

**Comment by ice9js** [comment]
But that's exactly what it does. It jumps as usual except for when you try to jump to a last character in a line. In that case it jumps behind it.

All you need to do is set `jump_behind_last_characters` to `true`. It's turned off by default.

Or is there anything else I am missing ?

**Comment by eorroe** [comment]
Oh no, you're right I thought it was a setting to change it where it always jumps after the character thanks!!!

**Comment by ice9js** [comment]
I'm glad I could help 😃
