### ISSUE TITLE
Support for "Within Line" motion

### ISSUE THREAD

**Issue by ghost** [ice9js/ace-jump-sublime#43]
Hi, thanks for a great plugin, I use it a lot. 

I come from Vim background and in Vim there is the Easymotion plugin which allows for within line motion, that is, which just one command, the beginning of each word in the current line is highlighted/marked so you just have to enter the key corresponding to the word you want to go to. I find this a bit faster than looking and typing for a particular character and then go to it.

It would be great if you can implement this feature in future versions of your plugin. Thanks!

**Comment by ice9js** [comment]
Sure, it doesn't sound like too much work. I'll try to add it whenever I have the time.

**Comment by ghost** [comment]
Thanks! Looking forward to it.
