### ISSUE TITLE
This is awesome, but some functions do not work 

### ISSUE THREAD

**Issue by luxueyan** [ice9js/ace-jump-sublime#44]
My computer is mac,version: 10.10.4
sublime version : 3114
"ace_jump_select,ace_jump_add_cursor,ace_jump_after" These commends do not work, though i set custom short-key for these commend.
Thanks for your help!

**Comment by ice9js** [comment]
Hi,

You need to use these commands in conjunction with character, word or line mode. So, for example, if I wanted to select some text, I would trigger the select mode by pressing `Ctrl+;`, and then I could press `Cmd+Shift+'` to select the text between the current cursor position and the letter I jump to.

Let me know if that solves your issue, as the readme might be a little unclear on this.

**Comment by luxueyan** [comment]
@ice9js  Thanks very much！I understood wrongly! It works!
