### ISSUE TITLE
AceJump won't jump to the last character of any line

### ISSUE THREAD

**Issue by terheyden** [ice9js/ace-jump-sublime#45]
Let's say you have some text.

> This
> is
> some text.

If you try to jump to "s", only the 3rd "s" will be available. The first two "s" are ignored because they are the last characters of the line.

---

Screenshot:

<img width="178" alt="untitled sublime text today at 8 19 06 pm" src="https://cloud.githubusercontent.com/assets/984174/16641612/54f2461c-43b7-11e6-8994-920f96149402.png">

**Comment by stoivo** [comment]
I am not the maintainer but I think I spotted your issue.

It looks like you are using the [word-mode](https://github.com/ice9js/ace-jump-sublime#word-mode), this will only look for the first character i a word.

I think you are looking for is [character-mode](https://github.com/ice9js/ace-jump-sublime#character-mode), goes to any character. `Ctrl/Super + Shift + '`

**Comment by terheyden** [comment]
Ah jeez, thanks.
