### ISSUE TITLE
In Line Mode,Last line is not labelled

### ISSUE THREAD

**Issue by rakshith98** [ice9js/ace-jump-sublime#70]
As seen below ,last line is not labelled in line mode even though it is not empty(line11).
![capture1](https://user-images.githubusercontent.com/26547534/31448928-3891ccf4-aec3-11e7-8b90-19859deba81a.JPG)

**Comment by ice9js** [comment]
I can confirm the issue, but as I'm a bit short on time right now - I'm adding the `pr welcome` label. Will try to get to it within the next month if time allows.

**Comment by Asuza** [comment]
@ice9js do you have time to merge this in and update the package?

**Comment by ice9js** [comment]
Done! Thank you for the ping - I totally forgot about this :/
