### ISSUE TITLE
Markers not showing with good contrast in Build 3149

### ISSUE THREAD

**Issue by jayliu50** [ice9js/ace-jump-sublime#71]
The nice, bright red background for the markers is lacking contrast in the recent builds that modify text highlighting:

![image](https://user-images.githubusercontent.com/673862/31564169-df7a8408-b02f-11e7-950d-fee5586ba655.png)

**Comment by ice9js** [comment]
Unfortunately, plugins can't 'just change' the colors - those are determined by your theme. You can however choose what 'scope' to use for the highlighting so there is a bigger contrast as explained in the [readme](https://github.com/ice9js/ace-jump-sublime#highlighting).  
You can also find a more detailed description of what you need to do in #33 which was an identical issue.

Closing this now but feel free to let me know if you have any trouble with changing the highlighting scope.
