### ISSUE TITLE
Key bindings overrides don't work

### ISSUE THREAD

**Issue by radzev1ch** [ice9js/ace-jump-sublime#74]
Sublime text  3  - Build 3143.

**Comment by ice9js** [comment]
Could you check if anything shows up in the console when using the said keybindings and post your findings here as well ?

**Comment by radzev1ch** [comment]
I reinstalled my sublime text and plugins. It's ok.

**Comment by ice9js** [comment]
Thanks for the update. Feel free to let us know if you run into anything else in the future.
