### ISSUE TITLE
Is there a way to turn off showing the "Char" panel

### ISSUE THREAD

**Issue by sourcevault** [ice9js/ace-jump-sublime#87]
The panel that is shown at the bottom is distracting.

It also takes up a lot of valuable screen real estate, especially on smaller monitors.

In Vim / [NeoVint](https://github.com/NeoVintageous/NeoVintageous/issues), **everything** is displayed in the status bar.

Would it be possible to do something similar for AceJump ?

https://github.com/ice9js/ace-jump-sublime/assets/20347647/b9fe1a1e-f4f1-4629-8bc3-6ddaa4e1f9c1

**Comment by stoivo** [comment]
Maybe it would be possible to hide the input after first entered and show it it the status bar instead but I don't think it would be so easy. 

Anyway, you can make the panel smaller by dragging it 

https://github.com/ice9js/ace-jump-sublime/assets/3492040/ded90a6c-bb69-4b7a-b307-c32ee1f147f0
